export const CREATE_VOLUNTEER = "CREATE_VOLUNTEER";
export const DELETE_VOLUNTEER = "DELETE_VOLUNTEER";
export const UPDATE_VOLUNTEER = "UPDATE_VOLUNTEER";
export const GET_ALL_VOLUNTEERS = "GET_ALL_VOLUNTEERS";
export const GET_ONE_VOLUNTEER = "GET_ONE_VOLUNTEER";
export const ERROR_GENERATED = "ERROR_GENERATED";