//Volunteers Reducer types
export const CREATE_VOLUNTEER = "CREATE_VOLUNTEER";
export const DELETE_VOLUNTEER = "DELETE_VOLUNTEER";
export const UPDATE_VOLUNTEER = "UPDATE_VOLUNTEER";
export const GET_ALL_VOLUNTEERS = "GET_ALL_VOLUNTEERS";
export const GET_ONE_VOLUNTEER = "GET_ONE_VOLUNTEER";
export const VOLUNTEER_SELECTED = "VOLUNTEER_SELECTED";
export const ERROR_GENERATED = "ERROR_GENERATED";

//Schedules Reducer types
export const CREATE_SCHEDULE = "CREATE_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const GET_ALL_SCHEDULES = "GET_ALL_SCHEDULES";
export const GET_ONE_SCHEDULE = "GET_ONE_SCHEDULE";
export const SCHEDULE_SELECTED = "SCHEDULE_SELECTED";
export const UPDATE_SCHEDULE = "UPDATE_SCHEDULE";

//SchedulesTemplate Reducer types
export const ADD_MINISTRY = "ADD_MINISTRY";
export const ADD_ROLE = "ADD_ROLE";
export const CHANGE_NUMBEROFSERVICES = "CHANGE_NUMBEROFSERVICES";
export const ADD_BACKGROUNDCHECK = "ADD_BACKGROUNDCHECK";
export const DELETE_ROLE = "DELETE_ROLE";
export const CHANGE_CREATEMINISTRYTITLE = "CHANGE_CREATEMINISTRYTITLE";
export const CLEAR_ROLESARRAY = 'CLEAR_ROLESARRAY';
// export const ADD_MINISTRY = "ADD_MINISTRY";
// export const ADD_MINISTRY = "ADD_MINISTRY";